### ISSUE TITLE
提交的表单信息中多了两个参数

### ISSUE THREAD

**Issue by FrazierLei** [Tishacy/BatchHitcarder#1]
两个参数写在index页面里，如果不加上这两个参数会提示 `请获取定位信息或者选取填写所在位置`，两个参数的变量名像是md5加密，值一个是时间戳，另一个也像是md5。我试了下用我的参数值也可以给别人打，LZ有空处理一下？

**Comment by Gavin-Yi** [comment]
自己改好了，没有pull权限，只能自己用了...

**Comment by Mythologyli** [comment]
> 自己改好了，没有pull权限，只能自己用了...

可以 Pull request
