### ISSUE TITLE
怎么指定打卡地址

### ISSUE THREAD

**Issue by Itachiiii** [Tishacy/BatchHitcarder#4]
没看到有address和area相关的参数

**Comment by Tishacy** [comment]
打卡地址使用的是上一次打卡的地址，所以需要至少手动打卡一次。如果需要更新打卡地址的话，当天手动打卡即可，后续打卡会自动按照你本次更新的地址继续打卡~

**Comment by Itachiiii** [comment]
> 打卡地址使用的是上一次打卡的地址，所以需要至少手动打卡一次。如果需要更新打卡地址的话，当天手动打卡即可，后续打卡会自动按照你本次更新的地址继续打卡~

这个获取地址时如果是手动选择的（不是钉钉自动获取定位），第二天自动打卡也是这个地址是八

**Comment by Tishacy** [comment]
是的~ 如果是手动选择了地址，自动打卡也会是这个地址。
